### ISSUE TITLE
error: lambda expressions are not supported in -source 6

### ISSUE THREAD

**Issue by jenni** [ohtu-intellij/tmc-intellij#140] opened 2018-08-09 19:15 UTC
Getting this error when using:

```
    public void printMeals() {
        this.meals.forEach(meal -> System.out.println(meal));
    }
```

It'd be nice if TMC supported Java 8 features :)

**Comment by rlmhermans** [comment] 2018-08-28 08:11
That is not so much up to TMC, as it is to the project file owners.

**Comment by nygrenh** [comment] 2018-08-28 09:57
Closing this as it is a duplicate of https://github.com/materiaalit/2013-oo-programming/issues/1

**Closed as completed by nygrenh** 2018-08-28 09:57 UTC
